-- Role: "CleanAdmin"
-- DROP ROLE IF EXISTS "CleanAdmin";

CREATE ROLE "CleanAdmin" WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  NOREPLICATION
  BYPASSRLS
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:/hnP2z4yP+50OFSmpHvpXw==$u8bDZiTCZrof9MEY1Au2P3e7fKDYZkYQtInE9l7IaJU=:NUpUcZzaZf5TjUVv6yE/8qGg9M3qyTICEsTs5iFlOMQ=';